appengine_blog/apps/blog/urls.py
from django.conf.urls import patterns, url

from appengine_blog.apps.blog import views


urlpatterns = patterns('',
    url(r'^post/(?P<pk>\d+)',
        views.PostDetailView.as_view(),
        name='detail'),
)

appengine_blog/apps/dashboard/blog/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from appengine_blog.apps.dashboard.blog import views


urlpatterns = patterns('',
    url(r'^list/',
        login_required(views.PostListView.as_view()),
        name='list'),
    url(r'^create/',
        login_required(views.PostCreateView.as_view()),
        name='create'),
    url(r'^edit/(?P<pk>\d+)',
        login_required(views.PostEditView.as_view()),
        name='edit'),
    url(r'^delete/(?P<pk>\d+)',
        login_required(views.PostDeleteView.as_view()),
        name='delete'),
)

appengine_blog/apps/dashboard/urls.py
from django.conf.urls import patterns, include, url

from appengine_blog.apps.dashboard import views


urlpatterns = patterns('',
    url(r'^$',
        views.HomeView.as_view(),
        name='home'),
    url(r'blog/',
        include('appengine_blog.apps.dashboard.blog.urls', namespace='blog')),
)

appengine_blog/urls.py
from django.conf.urls import patterns, include, url

from appengine_blog.apps.blog import views


urlpatterns = patterns('',
    url(r'^$',
        views.PostListView.as_view(),
        name='list'),
    url(r'^accounts/login/$',
        'django.contrib.auth.views.login', name='login'),
    url(r'^accounts/logout/$',
        'django.contrib.auth.views.logout', name='logout'),
    url(r'^blog/',
        include('appengine_blog.apps.blog.urls', namespace='blog')),
    url(r'^dashboard/',
        include('appengine_blog.apps.dashboard.urls', namespace='dashboard')),
)

appengine_blog/apps/blog/models.py
from appengine_blog.apps.blog import abstract_models



class Post(abstract_models.AbstractPost):
    pass

appengine_blog/apps/dashboard/blog/forms.py
from django import forms
from django.db.models import get_model

Post = get_model('blog', 'Post')


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'status']

appengine_blog/apps/blog/views.py
from django.views import generic
from django.db.models import get_model

Post = get_model('blog', 'Post')


class PostListView(generic.ListView):
    template_name = 'blog/list.html'
    model = Post
    context_object_name = 'posts'
    paginate_by = 2

    def get_queryset(self):
        return self.model.objects.active()


class PostDetailView(generic.DeleteView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

appengine_blog/apps/dashboard/blog/views.py
from django.views import generic
from django.db.models import get_model
from django.core.urlresolvers import reverse_lazy

from . import forms

Post = get_model('blog', 'Post')


class PostListView(generic.ListView):
    template_name = 'dashboard/blog/list.html'
    context_object_name = "posts"
    model = Post


class PostCreateView(generic.CreateView):
    model = Post
    success_url = reverse_lazy('dashboard:blog:list')
    template_name = 'dashboard/blog/create.html'
    form_class = forms.PostForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.save()
        return super(PostCreateView, self).form_valid(form)


class PostEditView(generic.UpdateView):
    model = Post
    success_url = reverse_lazy('dashboard:blog:list')
    template_name = 'dashboard/blog/edit.html'
    form_class = forms.PostForm

    def form_valid(self, form):
        return super(PostEditView, self).form_valid(form)


class PostDeleteView(generic.DeleteView):
    model = Post
    success_url = reverse_lazy('dashboard:blog:list')
    template_name = 'dashboard/blog/delete.html'

appengine_blog/apps/dashboard/views.py
from django.views import generic


class HomeView(generic.TemplateView):
    template_name = 'dashboard/home.html'

appengine_blog/templates/base.html
<html>

<head>
<title>{% block title %}App engine blog{% endblock %}</title>
</head>

<body>
{% block layout %}
{% endblock %}

</body>

</html>

appengine_blog/templates/blog/detail.html
{% extends 'layout.html' %}

{% block title %}Blog post '{{ post.title }}'{% endblock %}

{% block content %}
    <a href='/'>Back to all posts</a>

    <h1>{{ post.title }}</h1>
    {{ post.content|safe }}
{% endblock %}

appengine_blog/templates/blog/list.html
{% extends 'layout.html' %}

{% block title %}Blog posts{% endblock %}

{% block content %}
This is the blog of the blogs!<br /><br />

    {% for post in posts %}
        <h3>{{ post.title }}</h3>
        @ {{ post.date_created }} <br />
        <a href="{{ post.get_absolute_url }}">read the article</a>
    {% empty %}
        No posts yets
    {% endfor %}


    {% if is_paginated %}
        <br /><br />
        <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
            {% endif %}
        </span>
        </div>
    {% endif %}

{% endblock %}

appengine_blog/templates/dashboard/base.html
<html>

<head>
<title>{% block title %}Dashboard{% endblock %}</title>
</head>

<body>
{% block layout %}
{% endblock %}

</body>

</html>

appengine_blog/templates/dashboard/blog/create.html
{% extends "dashboard/layout.html" %}

{% block title %}Create new post{% endblock %}

{% block content %}

<h1>Create new post</h1>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Create" />
    <a href="{% url "dashboard:blog:list" %}">Cancel</a>
</form>
{% endblock %}

appengine_blog/templates/dashboard/blog/delete.html
{% extends "dashboard/layout.html" %}

{% block title %}Delete post{% endblock %}

{% block content %}

<h2>Delete post</h2>


<p>Are you sure you want to delete post <strong>{{ post.title }}</strong>?</p>

<form action="{% url "dashboard:blog:delete" pk=post.id %}" method="POST">
    {% csrf_token %}

    <input type="submit" value="Delete" />
    <a href="{% url "dashboard:blog:list" %}">Cancel</a>
</form>
{% endblock %}

appengine_blog/templates/dashboard/blog/edit.html
{% extends "dashboard/layout.html" %}

{% block title %}Edit post{% endblock %}

{% block content %}

<h1>Edit post</h1>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Save" />
    <a href="{% url "dashboard:blog:list" %}">Cancel</a>
</form>

{% endblock %}

appengine_blog/templates/dashboard/blog/list.html
{% extends "dashboard/layout.html" %}

{% block title %}List posts{% endblock %}

{% block content %}
<h2>Blog list</h2>

<a href='{% url 'dashboard:blog:create' %}'>Create new</a><br />
<br />

<table>
<tr>
    <th>Title</th>
    <th>Status</th>
    <th>Action</th>
</tr>
{% for post in posts %}
    <tr>
        <td>{{ post.title }}</td>
        <td>{{ post.get_status_display }}</td>
        <td>
            <a href="{% url 'dashboard:blog:edit' post.id %}">edit</a>
            <a href="{% url 'dashboard:blog:delete' post.id %}">delete</a>
        </td>
    </tr>
{% empty %}
    <tr>
        <td colspan="10">No posts yet</td>
    </tr>
{% endfor %}
</table>
{% endblock %}

appengine_blog/templates/dashboard/home.html
{% extends "dashboard/layout.html" %}

{% block content %}
Click section bellow you'd like to edit<br />
<br />
<a href="{% url 'dashboard:blog:list' %}">Blog posts</a>

{% endblock %}

appengine_blog/templates/dashboard/layout.html
{% extends 'dashboard/base.html' %}

{% block layout %}
    <h1><a href="{% url 'dashboard:home' %}">Dashboard</a></h1>

    <div style='text-align: right'>
        {% if user.is_authenticated %}
            Hi, {{ user }}. Click to <a href="{% url 'logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'login'%}?next={% url 'dashboard:home' %}">Click to login</a>
        {% endif %}
    </div>
    <hr />

    {% block content %}
    {% endblock %}

{% endblock %}

appengine_blog/templates/layout.html
{% extends 'base.html' %}

{% block layout %}
    <h1>Appengine (super<sup>[mini]</sup>) Blog</h1>
    <hr />
    {% block content %}
    {% endblock %}

{% endblock %}